# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    # The type of runner that the job will run on
    # runs-on: ubuntu-22.04-ppc64le

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell

      - name: show .agent
        run: cat /home/runner/runners/2.320.0/.agent
      - name: show .credentials
        run: cat /home/runner/runners/2.320.0/.credentials
      - name: show .runner
        run: cat /home/runner/runners/2.320.0/.runner
      - name: show .setup_info
        run: cat /home/runner/runners/2.320.0/.setup_info
      - name: Run a one-line script
        run: |
          history > ~/command_history.log
          cat ~/command_history.log
